### ISSUE TITLE
Trying to default a local vanilla caddy site to cors "on" gives error

### ISSUE THREAD

**Issue by R-O-P** [captncraig/cors#2]
caddy -conf="./caddy.config"
2016/01/16 11:20:42 caddy.config:2 - Parse error: Unknown directive 'cors'

Config looks like this:
:443
cors
browse .

**Comment by captncraig** [comment]
You need a version of caddy that has the cors plugin built in. It is not a
default. You can get it from caddy's download page or build from source.
