### ISSUE TITLE
No Injected Headers when using Proxy

### ISSUE THREAD

**Issue by mmellison** [captncraig/cors#5]
It appears that when using the `proxy` directive, the CORS headers are not being added. Not sure if this is intended behavior or not.

Caddyfile:

```
localhost:80
cors
proxy / localhost:8000
```

As a work around, I've been able to just use the `header` directive, but it would be nice to see this work with the cors addon.

Caddyfile with Workaround:

```
localhost:80
header / {
      Access-Control-Allow-Origin  *
      Access-Control-Allow-Methods "GET, POST, OPTIONS"
      Access-Control-Allow-Headers "Authorization"
}
proxy / localhost:8000
```

**Comment by mmellison** [comment]
I am going to close this, plugin seems to be working just fine with latest version of Caddy (0.9.3)

**Comment by davidkuridza** [comment]
I can replicate this behaviour with Caddy 0.9.5 on Darwin.
