### ISSUE TITLE
Update to 0.9 plugin format

### ISSUE THREAD

**Issue by mholt** [captncraig/cors#6]
I forgot to leave a PR here, but until this plugin is updated for the Caddy 0.9 format I can't include it on the download page. Sorry for the inconvenience. :-/

**Comment by princemaple** [comment]
@captncraig hi, would you be working on this any time soon?

**Comment by captncraig** [comment]
Pushed changes just now to master. @mholt can you update buildsrv?

**Comment by mholt** [comment]
[This line](https://github.com/captncraig/cors/blob/5e578a586279cf5832a6d3ba6b92d537bd6f2807/caddy/corsPlugin.go#L30) doesn't build - remove the `.Key` part. See [the wiki article on converting plugins](https://github.com/mholt/caddy/wiki/Converting-Add-ons-to-Plugins).

Thanks for working on it. :)

**Comment by princemaple** [comment]
ping @mholt https://github.com/captncraig/cors/commit/b085be4d2c013a94cc25a0227d618b8108a2ed88

**Comment by mholt** [comment]
Got it, thanks! Will update the build server with the next Caddy release.
