### ISSUE TITLE
Calling next middleware on failed CORS request

### ISSUE THREAD

**Issue by stp-ip** [captncraig/cors#8]
Thanks for providing this plugin. Always great to see open source efforts coming together.

Recently I ran into an issue with mailout (or at least I thought it was the issue source). I'm using CORS to prevent other sides from requesting/sending emails and therefore used the cors plugin.

Config:
```
cors / https://example.com
```
So only requests from example.com should be able to send mail/request/post to the given url.
The result is that the request seems to fail on the client-side with:
```
XMLHttpRequest cannot load https://mailout.example.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1313' is therefore not allowed access.
jquery.min.js:4 XHR failed loading: POST "https://mailout.example.com/".
```

What I thought would happen:
No email would be send and an error would be returned for the request.

What happened:
Email was sent (mailout middleware was called), POST request returned 200.

Might that be an issue with how the CORS middleware handles this or should am I doing something strange on the clientside?

For reference: [mailout issue](https://github.com/SchumacherFM/mailout/issues/11)

**Comment by stp-ip** [comment]
Seems fixed in recent releases.

**Comment by stp-ip** [comment]
Sorry have to reopen as the fix wasn't related to cors. This issue still persists.

**Comment by captncraig** [comment]
Sorry I'm a bit late. I'm afraid I'm not clear on the reproduction procedure here. Are you saying a browser request from an unauthorized domain is receiving valid `Access-Control-Allow-Origin` headers? 

I'm not quite clear on which request you think is calling the next middleware inappropriately. The preflight request should be the only request that happens, and if that is handled correctly, no other middlewares should be called. After that, your browser is responsible for blocking the rest unless valid headers are received.

**Comment by stp-ip** [comment]
Ok. Will look into it again and try to get more context for something reproducible. Thanks for taking the time.

**Comment by stp-ip** [comment]
Seems to work as expected now. Thanks for all the work.
