### ISSUE TITLE
Submit this plugin to the new Caddy website

### ISSUE THREAD

**Issue by mholt** [captncraig/cors#9]
Is there anything I can do to help you add this and your other plugins to the new Caddy site? It should make things easier for you in the long run, at least, that's my hope.

I know you've been super busy with the DNS stuff for Stack (which is fabulous, by the way) -- I just wanted to check in and make sure there's nothing else I can do before April 20 to convince you. :)

**Comment by captncraig** [comment]
All right, I'll tackle it tonight. Planning to go to your party too.

**Comment by mholt** [comment]
Oh, perfect -- I was just writing an email to you about that, to personally invite you.

*crossing my fingers everything works*
